server {
    listen 80;
    server_name vod-ka.bet www.vod-ka.bet;
    return 301 https://www.vod-ka.bet$request_uri;
}

server {
    listen 443 ssl;
    server_name www.vod-ka.bet;

    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_proxied any;
    gzip_min_length 1000;

    location /api-proxy/ {
        rewrite ^/api-proxy/(.*) /$1 break;
        
        proxy_pass https://vodka.bet;
        
        proxy_set_header Host vodka.bet;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        add_header 'Access-Control-Allow-Origin' 'https://www.vod-ka.bet' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
    }

    location / {
        root /var/www/html;
        index index.html;
    }

    location ~* \.(png|jpg|jpeg|gif|ico|webp|svg)$ {
        expires 6M;
        access_log off;
    }
}
